"""
models/insight.py
-----------------
Insight model: stores rule-based financial messages generated by the insight engine.
Insights are tied to a specific month/year and can be marked as read.
"""

from datetime import datetime
from ..extensions import db


class Insight(db.Model):
    __tablename__ = "insights"

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id", ondelete="CASCADE"), nullable=False)

    # Insight type key (e.g. 'budget_exceeded', 'top_category', 'savings_below_target')
    type = db.Column(db.String(50), nullable=False)
    message = db.Column(db.Text, nullable=False)

    # 'info' | 'warning' | 'critical'
    severity = db.Column(db.String(20), default="info")

    month = db.Column(db.Integer, nullable=False)
    year = db.Column(db.Integer, nullable=False)
    is_read = db.Column(db.Boolean, default=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "type": self.type,
            "message": self.message,
            "severity": self.severity,
            "month": self.month,
            "year": self.year,
            "is_read": self.is_read,
            "created_at": self.created_at.isoformat(),
        }

    def __repr__(self):
        return f"<Insight [{self.severity}] {self.type}>"
